version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: your_mac_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: your_mac_username
      SPRING_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge